#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2024.2.2 (64-bit)
#
# Filename    : compile.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for compiling the simulation design source files
#
# Generated by Vivado on Sun Jul 13 18:55:45 +04 2025
# SW Build 6060944 on Thu Mar 06 19:10:09 MST 2025
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: compile.sh
#
# ****************************************************************************
set -Eeuo pipefail
# compile Verilog/System Verilog design sources
echo "xvlog --incr --relax -prj tb_manchester_encoder_vlog.prj"
xvlog --incr --relax -prj tb_manchester_encoder_vlog.prj 2>&1 | tee compile.log

echo "Waiting for jobs to finish..."
echo "No pending jobs, compilation finished."
