-d /home/dev/dev/fpga/projects/manchester/gowin/manchester/impl/gwsynthesis/manchester.vg
-p GW2AR-18C-QFN88-8
-pn GW2AR-LV18QN88C8/I7
-cst /home/dev/dev/fpga/projects/manchester/const/tang_nano_9k.cst
-cfg /home/dev/dev/fpga/projects/manchester/gowin/manchester/impl/pnr/device.cfg
-sdc /home/dev/dev/fpga/projects/manchester/gowin/manchester/src/time_consts.sdc
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-place_option 0
-route_option 0
-clock_route_order 0
-correct_hold 1
-route_maxfan 23
-global_freq 100.000
